// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/sevigo/hokan/cmd/hokan/config"
	"github.com/sevigo/hokan/pkg/handler/api"
)

// Injectors from wire.go:

func InitializeApplication(ctx context.Context, config2 config.Config) (application, error) {
	db, err := provideDatabase(config2)
	if err != nil {
		return application{}, err
	}
	directoryStore := provideDirectoryStore(db)
	eventCreator := provideEventCreator()
	server := api.New(directoryStore, eventCreator)
	mainHealthzHandler := provideHealthz()
	handler := provideRouter(server, mainHealthzHandler)
	serverServer := provideServer(handler, config2)
	watcher, err := provideWatcher(ctx, directoryStore, eventCreator)
	if err != nil {
		return application{}, err
	}
	mainApplication := newApplication(serverServer, directoryStore, watcher)
	return mainApplication, nil
}
