// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/sevigo/hokan/cmd/hokan/config"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	mainHealthzHandler := provideHealthz()
	mux := provideRouter(mainHealthzHandler)
	server := provideServer(mux, config2)
	mainApplication := newApplication(server)
	return mainApplication, nil
}
